[package]
name = "test-http"
version = "1.0.0"
authors = ["Ekjot Singh <ekjotmakhija@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "test-http, run and test HTTP requests"
documentation = "https://example.com"
homepage = "https://example.com"
repository = "https://github.com/Orange-OpenSource/hurl"
rust-version = "1.91.1"

[lib]
name = "test_http"

[[bin]]
name = "test-http"
path = "src/main.rs"

[features]
# Re-export of curl/static-ssl: use a bundled OpenSSL version and statically link to it.
static-openssl = ["curl/static-ssl", "curl-sys/static-ssl"]

[dependencies]
base64 = "0.22.1"
brotli = "8.0.2"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
clap = { version = "4.5.51", features = ["string", "wrap_help"] }
curl = "0.4.49"
curl-sys = "0.4.84"
encoding_rs = "0.8.35"
glob = "0.3.3"
test-http-core = { version = "1.0.0", path = "../test-http-core" }
libflate = "2.2.1"
libxml = "0.3.8"
md5 = "0.7.0"
percent-encoding = "2.3.2"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["arbitrary_precision"] }
sha2 = "0.10.9"
url = "2.5.7"
xml-rs = { version = "0.8.28" }
uuid = { version = "1.18.1", features = ["v4" , "fast-rng"] }
similar = "2.7.0"
terminal_size = "0.4.3"

[target.'cfg(unix)'.dependencies]
termion = "4.0.5"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[build-dependencies]
cc = "1.2.46"

[lints]
workspace = true
